spring.application.name=Furniture-Store
spring.datasource.url=jdbc:postgresql://localhost:5432/Furniture-store
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
server.port =9099
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.boot.autoconfigure=DEBUG
spring.main.lazy-initialization=true